name: Contributors

on:
  schedule:
    - cron: '18 4 * * 6'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  contributors:
    permissions:
      pull-requests: write
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/contributors.yml@9f8b5be8a961946631c7b7f0ba3e103600135388 # v0.2.3
    secrets: inherit
